config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  def found_days_ago
    (Date.today - found_on).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to pet_path(@pet)
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetsPrep</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="container mt-5">
  <%= simple_form_for @pet do |f| %>
  <%= f.label :name, "Enter a name" %>
  <%= f.input :name, label: false %>
  <%= f.input :address %>
  <%= f.input :species %>
  <%= f.input :found_on, as: :date %>
  <%= f.button :submit, class: 'btn btn-danger w-100' %>
  <% end %>
</div>

app/views/pets/edit.html.erb
<%= render "form" %>

app/views/pets/index.html.erb
<div class="container">
  <ul>
    <% @pets.each do |pet| %>
    <li>
      <h1><%= link_to pet.name, pet_path(pet) %></h1>
      <h2><%= pet.species %></h2>
      <h2>Found <%= pet.found_days_ago %> days ago</h2>
      <%= link_to "edit", edit_pet_path(pet) %>
    </li>
    <% end %>
  </ul>

  <%= link_to "Add a pet", new_pet_path, class: "btn btn-primary" %>

</div>

app/views/pets/new.html.erb
<%= render "form" %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<h3><%= @pet.species %></h3>
<h3><%= @pet.address %></h3>
<h3>Found <%= @pet.found_days_ago %> days ago</h3>
<%= link_to "delete", pet_path(@pet), method: :delete %>
<%= link_to "See all pets", pets_path %>